name: 'Tests'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        go: [ '1.20' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Set up gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
      - name: Run tests
        run: go test -covermode=atomic -coverprofile=coverage.txt -timeout 5m -json -v ./... | gotestfmt -showteststatus
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          flags: tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
